# Settings configuration:

DefaultRank: "Default"
UseTabPrefix: true
UpdateNotifier: true
# If this is set to true, it'll automatically deop and op players.
# They'll be opped and deop by looking at their rank.
AutoOperator: true

# Modifiers for different events happening in the server.
Modifiers:
  World:
    # Can add different worlds here as well.
    # Examples for world "World" (as shown below).
    Weather:
      World:
        Change: false
        # Ony works if change is set to false.
        # Weather types: SUN, RAIN and STORM.
        LockTo: "SUN"
    Time:
      World:
        Change: false
        # Only works if change is set to false.
        # Any number you'd provide in the /time command.
        LockTo: 1700